before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - psql -c 'create database CampusHunter_test;' -U postgres
  - rake db:test:load
  - rake db:migrate


language: ruby
rvm:
  - "1.9.3"
  # uncomment this line if your project needs to run something other than `rake`:

script:

  - rake cucumber --trace
